global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: embeddings-gateway
    metrics_path: /gateway/metrics
    static_configs:
      - targets: ["embeddings-gateway:8080"]
